[package]
name = "stun_bytes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
endianeer = { path = "../endianeer", default-features = false, features = ["u16", "carve"] }
