[package]
name = "stun_client"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.16" }
stun_proto = { path = "../stun_proto" }

[dev-dependencies]
pretty_env_logger = { version = "0.4.0" }
