[package]
name = "stun-bytes"
version = "0.1.0"
edition = "2021"

[features]
mut = []
default = []

[dependencies]
r-ex = { version = "1.0.0", features = ["endian", "carve", "copy-from", "from-arr", "splice"] }
